#!/bin/bash   

#PBS -l nodes=1:ppn=16
#PBS -l walltime=03:00:00
#PBS -N pan_trog
#PBS -o pan_trog.output
#PBS -e pan_trog.error
#PBS -m abe 
#PBS -M llnguyen@iu.edu
 

cd $PBS_O_WORKDIR 

module load ants

antsMultivariateTemplateConstruction2.sh -d 3 -o /N/dc2/scratch/llnguyen/schoenemann/pan_trog/pan_trog_test/results/T_ \
  -i 3 -k 1 -n 0 -f 4x2x1 \
  -y 0 -z init.nii.gz -s 2x1x0vox -q 30x10x0 -t SyN  -m MSQ  *.nii.gz

echo 0>finished
